# Generated by Django 3.2.3 on 2021-05-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCorridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.floor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCorridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.floor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('consumption_unit', models.IntegerField(default=5)),
                ('turned_on', models.BooleanField(default=True)),
                ('main_corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.maincorridor')),
                ('sub_corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.subcorridor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('consumption_unit', models.IntegerField(default=5)),
                ('turned_on', models.BooleanField(default=True)),
                ('main_corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.maincorridor')),
                ('sub_corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.subcorridor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
