# Generated by Django 3.2.3 on 2021-05-17 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210517_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.BooleanField(default=False)),
                ('sub_corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.subcorridor')),
            ],
        ),
    ]
