# Generated by Django 3.1.11 on 2021-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20210517_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motiondetection',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='motiondetection',
            name='action_timestamp',
        ),
        migrations.AddField(
            model_name='motiondetection',
            name='action_1_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motiondetection',
            name='action_2_taken',
            field=models.BooleanField(default=False),
        ),
    ]
