# Generated by Django 3.2.3 on 2021-05-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_floorpowerconsumptionperhour_units_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioner',
            name='consumption_unit',
        ),
        migrations.RemoveField(
            model_name='light',
            name='consumption_unit',
        ),
    ]
