# Generated by Django 3.2.3 on 2021-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20210531_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='extreme_power_saver',
            field=models.BooleanField(default=False),
        ),
    ]
