# Generated by Django 3.2.3 on 2021-05-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_floor_extreme_power_saver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('turned_on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power_consumption_unit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='light',
            name='main_corridor',
        ),
        migrations.RemoveField(
            model_name='light',
            name='sub_corridor',
        ),
        migrations.DeleteModel(
            name='AirConditioner',
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.appliancetype'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='main_corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.maincorridor'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='sub_corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.subcorridor'),
        ),
    ]
