# Generated by Django 3.2.3 on 2021-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    def add_appliance_types(app, schema_editor):
        ApplianceType = app.get_model('hotel', 'ApplianceType')

        ApplianceType.objects.create(type='LIGHT',name='Light',power_consumption_unit=5)
        ApplianceType.objects.create(type='AIR_CONDITIONER',name='Air Conditioner',power_consumption_unit=10)

    dependencies = [
        ('hotel', '0011_auto_20210531_1652'),
    ]

    operations = [
        migrations.RunPython(add_appliance_types,
                             reverse_code=migrations.RunPython.noop),
    ]
