# Generated by Django 3.2.3 on 2021-05-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20210531_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorridorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcorridor',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='main_corridor',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='sub_corridor',
        ),
        migrations.RemoveField(
            model_name='motiondetection',
            name='sub_corridor',
        ),
        migrations.DeleteModel(
            name='MainCorridor',
        ),
        migrations.DeleteModel(
            name='SubCorridor',
        ),
        migrations.AddField(
            model_name='corridor',
            name='corridor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.corridortype'),
        ),
        migrations.AddField(
            model_name='corridor',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.floor'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.corridor'),
        ),
        migrations.AddField(
            model_name='motiondetection',
            name='corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.corridor'),
        ),
    ]
