# Generated by Django 3.2.3 on 2021-05-31 12:51
from django.db import migrations


class Migration(migrations.Migration):

    def add_corridor_types(app, schema_editor):
        CorridorType = app.get_model('hotel', 'CorridorType')
        CorridorType.objects.create(type='MAIN_CORRIDOR',name='Main Corridor')
        CorridorType.objects.create(type='SUB_CORRIDOR',name='Sub Corridor')

    dependencies = [
        ('hotel', '0013_auto_20210531_1821'),
    ]

    operations = [
        migrations.RunPython(add_corridor_types,
                             reverse_code=migrations.RunPython.noop),
    ]
